server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods: "*"
      #       allowedHeaders: "*"
      #       allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: authorization-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/authorization/**
          filters:
            - StripPrefix=1
                
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
jwt:
  secret: YW5kMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==