server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      # ===== Global CORS Configuration =====
      # globalcors:

      #   add-to-simple-url-handler-mapping: true  
      #   cors-configurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true

      # 2. Deduplicate any CORS headers that might come back from downstream

      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials,RETAIN_UNIQUE    
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods: "*"
      #       allowedHeaders: "*"
      #       allowCredentials: true  52.77.99.18

      routes:
        - id: auth-service
          # uri: http://localhost:8081 
          uri: http://52.77.99.18:8081 
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        # - id: authorization-service
        #   # uri: http://localhost:8082 
        #   uri: http://52.77.99.18:8082 
        #   predicates:
        #     - Path=/api/authorization/**
        #   filters:
        #     - StripPrefix=1
        #     - JwtAuthenticationFilter


eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: YW5kMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==