server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      # ===== Global CORS Configuration =====
      # globalcors:

      #   add-to-simple-url-handler-mapping: true  
      #   cors-configurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true

      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials,RETAIN_UNIQUE    
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods: "*"
      #       allowedHeaders: "*"
      #       allowCredentials: true  52.77.99.18

      routes:
        - id: auth-service
          # uri: http://localhost:8081 
          uri: http://52.77.99.18:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: user_detail_register
          uri: http://localhost:8083
          predicates:
            - Path=/api/user-details/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: ExaminationService
          uri: http://localhost:8084
          predicates:
            - Path=/api/examination/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: customer_registration
          uri: http://54.251.178.246:8080
          predicates:
            - Path=/api/customer/registration/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: YW5kMTIzNDU2Nzg5MGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==
